# Generated by Django 5.2.12 on 2026-04-03 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('organisation_id', models.UUIDField()),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('KYC_CASE', 'KYC Case'), ('BUSINESS', 'Business'), ('SYSTEM', 'System')], max_length=20)),
                ('owner_id', models.UUIDField()),
                ('uploaded_by_user_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, default='', max_length=20)),
                ('size_bytes', models.BigIntegerField()),
                ('file_hash_sha256', models.CharField(max_length=128)),
                ('storage_provider', models.CharField(choices=[('LOCAL', 'Local'), ('S3', 'S3'), ('GCS', 'GCS'), ('AZURE', 'Azure')], max_length=10)),
                ('storage_bucket', models.CharField(blank=True, default='', max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('category', models.CharField(choices=[('PROFILE_PICTURE', 'Profile Picture'), ('KYC_DOCUMENT', 'KYC Document'), ('SELFIE', 'Selfie'), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('SALARY_CERTIFICATE', 'Salary Certificate'), ('BANK_STATEMENT', 'Bank Statement'), ('TAX_RETURN', 'Tax Return'), ('TRADE_LICENCE', 'Trade Licence'), ('CONSENT', 'Consent'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('SCANNED', 'Scanned'), ('FAILED', 'Failed'), ('QUARANTINED', 'Quarantined'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('virus_scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('encrypted_at_rest', models.BooleanField(default=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploads',
                'indexes': [models.Index(fields=['organisation_id', 'owner_type', 'owner_id'], name='idx_uploads_org_owner'), models.Index(fields=['category'], name='idx_uploads_category'), models.Index(fields=['status'], name='idx_uploads_status')],
            },
        ),
    ]
